version: '3.8'

services:
  app_spring:
    build: .
#    ports:
#      - "8080:8080"
    restart: unless-stopped
#    environment:
#      - MYSQL_ROOT_PASSWORD=secret
#      - MYSQL_DATABASE=product_service
#    depends_on:
#      - mysqlapp
    networks:
      app-network:
        aliases:
          - app_spring

  mysqlapp:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_service
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      app-network:
        aliases:
          - mysqlapp

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
