version: '3.8'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    volumes:
      - ./elk:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    environment:
      - "discovery.type=single-node"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
