
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/produit-service?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
  mvc:
    log-request-details: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/my_real
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
logging:
  file:
    name: elk/spring.log
server:
  port: 8080
jwt:
  auth:
    converter:
      resource-id: my_rest_api
      principle-attribute: preferred_username